### ISSUE TITLE
LinearAlgebra::LectureNotes --tiny-- numbering mismatch

### ISSUE THREAD

**Issue by Islam0mar** [DrWaleedAYousef/Teaching#1] opened 2019-04-08 04:21 UTC
In LinearAlgebra::LectureNotes p25 section 2.3.5 Matrix Multiplication:
numbering is:

> 1. A m×1 , B 1×p .
> 2. A 1×n , B n×p .
> 3. A 1×n , B n×1 .
> 4. A m×n , B n×1 .

then on p28 :

> 3- As linear combinations of rows of B

p29 :

> 4- As summation of outer products, each is a matrix

Regards.

**Comment by DrWaleedAYousef** [comment] 2019-04-08 08:35
First of all, thanks so much for asking here on the repo instead of the channel. You are the first one to do this professional thing. This will make it easier for answering questions (since others may help me) and more educational for other students (since they will find all question at the same place).

Second, sorry where is the typo? I do not see it!

**Comment by Islam0mar** [comment] 2019-04-08 19:05
Actually this is strange, I am the one who should thank you for your work and effort to make this available!

uh..ohh, I removed it --was my mistake "subdevide" I just followed auto-correct--.

Regards.

**Comment by DrWaleedAYousef** [comment] 2019-04-08 19:34
I am not sure what do you mean! But it seems that the issue is solved. If so please close it. Thanks.

**Closed as completed** 2019-04-08 19:57 UTC
Labels: Linear Algebra
